# Generated by Django 4.0 on 2021-12-28 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_on',
            field=models.DateTimeField(default=datetime.date(2021, 12, 28)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_open_date',
            field=models.DateField(default=datetime.date(2021, 12, 28)),
        ),
    ]
