# Generated by Django 4.0 on 2022-01-10 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_comment_com_on_alter_listing_listing_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_on',
            field=models.DateTimeField(default=datetime.date(2022, 1, 10)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_open_date',
            field=models.DateField(default=datetime.date(2022, 1, 10)),
        ),
    ]
