# Generated by Django 4.1.7 on 2023-03-10 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist_item_id_alter_watchlist_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_on',
            field=models.DateTimeField(default=datetime.date(2023, 3, 10)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_open_date',
            field=models.DateField(default=datetime.date(2023, 3, 10)),
        ),
    ]
